from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('helvetica', '', 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, f'AgentShield - Mid-Semester Presentation Dossier | VIT Pune - Page {self.page_no()}', align='R', new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-20)
            self.set_font('helvetica', 'I', 9)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, 'Department of Computer Engineering | Group TYG19 | Guide: Prof. Sanyukta Deshmukh', align='C')

    def slide_title(self, title):
        self.set_fill_color(20, 30, 60)
        self.set_text_color(255, 255, 255)
        self.set_font('helvetica', 'B', 12)
        self.cell(0, 12, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def slide_section(self, title):
        self.set_text_color(0, 0, 0)
        self.set_font('helvetica', 'B', 11)
        self.cell(0, 8, title, border='B', new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def bullet_point(self, text):
        self.set_text_color(40, 40, 40)
        self.set_font('helvetica', '', 10)
        self.multi_cell(0, 6, f"-{text}")
        self.ln(1)
        
    def speaker_notes(self, text):
        self.ln(5)
        self.set_fill_color(255, 245, 230)
        self.set_text_color(180, 100, 0)
        self.set_font('helvetica', 'B', 10)
        self.cell(0, 8, "  SPEAKER NOTES & FACULTY EXAMINER TALKING POINTS:", fill=True, new_x="LMARGIN", new_y="NEXT", border="LTR")
        self.set_text_color(0, 0, 0)
        self.set_font('helvetica', '', 9)
        self.multi_cell(0, 5, text, fill=True, border="LBR")

pdf = PDF()
pdf.add_page()
pdf.set_fill_color(20, 30, 60)
pdf.set_text_color(255, 255, 255)
pdf.set_font('helvetica', 'B', 18)
pdf.cell(0, 15, "AgentShield: Mid-Sem Review Presentation Dossier", align='C', fill=True, new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 12)
pdf.cell(0, 10, "5-Slide Executive Academic Deck & Evaluation Criteria Assessment", align='C', fill=True, new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 10, "Aligned with VIT FF No. 180 Progress Review 1 Parameters", align='C', fill=True, new_x="LMARGIN", new_y="NEXT")
pdf.ln(10)

pdf.set_text_color(0, 0, 0)
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, "ACADEMIC & INSTITUTIONAL PROFILE", border='B', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 10)
pdf.ln(3)
pdf.cell(50, 6, "Institution:")
pdf.cell(0, 6, "Vishwakarma Institute of Technology (VIT), Pune", new_x="LMARGIN", new_y="NEXT")
pdf.cell(50, 6, "Department:")
pdf.cell(0, 6, "Department of Computer Engineering (Academic Year 2026-27)", new_x="LMARGIN", new_y="NEXT")
pdf.cell(50, 6, "Semester / Group:")
pdf.cell(0, 6, "Semester 5 | Group No.: TYG19 | Area: AI & Cybersecurity", new_x="LMARGIN", new_y="NEXT")
pdf.cell(50, 6, "Project Title:")
pdf.cell(0, 6, "AgentShield: A Dynamic Risk-Aware Security Framework for the Model Context Protocol", new_x="LMARGIN", new_y="NEXT")
pdf.cell(50, 6, "Faculty Guide:")
pdf.cell(0, 6, "Prof. Sanyukta Deshmukh", new_x="LMARGIN", new_y="NEXT")
pdf.ln(10)

pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, "GROUP MEMBERS & INDIVIDUAL RESPONSIBILITIES", border='B', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('helvetica', '', 10)
pdf.ln(3)
pdf.cell(60, 6, "1. Harsh Manjramkar (Roll 70):")
pdf.cell(0, 6, "Team Lead, Core Architecture & Custom Terminal Frontend", new_x="LMARGIN", new_y="NEXT")
pdf.cell(60, 6, "2. Vedant Gaidhani (Roll 74):")
pdf.cell(0, 6, "Security Engineer - Regex Detection & Dynamic Heuristics", new_x="LMARGIN", new_y="NEXT")
pdf.cell(60, 6, "3. Vineet Wagh (Roll 75):")
pdf.cell(0, 6, "Security Engineer - PII Sanitization & Dashboard UI/UX", new_x="LMARGIN", new_y="NEXT")
pdf.cell(60, 6, "4. Arjun Joshi (Roll 76):")
pdf.cell(0, 6, "QA Engineer - Automated PyTest Suite & Enterprise Mocking", new_x="LMARGIN", new_y="NEXT")
pdf.ln(10)

pdf.add_page()
pdf.slide_title("SLIDE 1 OF 5: Project Overview, Objectives & Team Responsibilities")
pdf.slide_section("Project Context & Domain")
pdf.bullet_point("Title: AgentShield: A Dynamic Risk-Aware Security Framework for the Model Context Protocol.")
pdf.bullet_point("Team Roles: Harsh (Core/Frontend), Vedant (Inbound Risk/Detectors), Vineet (Outbound PII/UI), Arjun (QA/Testing).")
pdf.slide_section("Problem Definition & Architectural Complexity")
pdf.bullet_point("Problem Statement: Direct point-to-point integration of AI agents with enterprise tools (databases, filesystems) via MCP introduces critical runtime vulnerabilities due to hallucinations and prompt injections.")
pdf.bullet_point("Complexity: The security gateway must inspect bidirectional JSON-RPC payloads in real time, evaluating multi-variable risk heuristics synchronously while maintaining low latency.")
pdf.speaker_notes("Good morning respected guide Prof. Sanyukta Deshmukh and committee. Slide 1 establishes our team allocation and problem definition. MCP grants AI direct tool execution rights. AgentShield provides the missing runtime guardrail without adding perceptible latency.")

pdf.add_page()
pdf.slide_title("SLIDE 2 OF 5: Literature Review, Related Work & Proposed Solution")
pdf.slide_section("Literature Survey & Critical Gaps")
pdf.bullet_point("MCPShield (2026): Evaluates historical server trust; Limitation: Static pre-handshake checks only.")
pdf.bullet_point("MCPSec (2026): Protocol-level encryption; Limitation: Cannot inspect or govern semantic agent actions.")
pdf.slide_section("Proposed Solution: Transparent Runtime Security Gateway")
pdf.bullet_point("Architecture: AgentShield acts as a smart reverse proxy between AI clients and target MCP servers.")
pdf.bullet_point("Dynamic Risk Governance: 3-Tier Security Engine using Regex, Heuristics, and PII redaction algorithms.")
pdf.bullet_point("Zero-Trust Human Oversight: Pauses dangerous commands for administrator sign-off via a visual dashboard.")
pdf.speaker_notes("Slide 2 presents our literature study. Existing 2025-2026 research focuses purely on transport encryption. AgentShield bridges this gap with an active runtime proxy that evaluates semantics, pauses for human approval, and sanitizes responses.")

pdf.add_page()
pdf.slide_title("SLIDE 3 OF 5: System Architecture & Methodology")
pdf.slide_section("System Architecture & Request Lifecycle")
pdf.bullet_point("1. Inbound Interceptor -> Captures JSON-RPC 2.0 requests at /mcp/v1/proxy.")
pdf.bullet_point("2. Dynamic Risk Classifier -> Analyzes method, tool name, and payload.")
pdf.bullet_point("3. Heuristic Detectors -> Scans arguments for injection tags, SQLi, and wildcard shell commands.")
pdf.bullet_point("4. Decision Gate -> LOW: Forward | INJECTION: Block instantly | SENSITIVE TOOL: Hold for HITL.")
pdf.bullet_point("5. Response PII Sanitizer -> Deep recursive object walker redacts sensitive data (Aadhaar, API keys).")
pdf.slide_section("Technology Stack")
pdf.bullet_point("Backend: Python 3.10+, FastAPI, Starlette (Async ASGI for high concurrency).")
pdf.bullet_point("Frontend: Interactive Dashboard with live custom terminal testing integration.")
pdf.speaker_notes("Slide 3 details our architecture. Every request passes through interception, risk scoring, heuristic analysis, decision gating, forwarding, and PII sanitization.")

pdf.add_page()
pdf.slide_title("SLIDE 4 OF 5: Cost, Resources & Sustainability")
pdf.slide_section("Cost Efficiency & Zero SaaS Dependencies")
pdf.bullet_point("100% Open-Source Stack: Constructed using Python and FastAPI with zero commercial licensing fees.")
pdf.bullet_point("Elimination of Third-Party API Costs: Regex automata and heuristic risk engines run locally in memory without querying costly external LLM APIs.")
pdf.slide_section("Environmental Relevance (Loop Suppression)")
pdf.bullet_point("Preventing AI Token Waste: Autonomous agents frequently enter infinite hallucination loops. AgentShield blocks and isolates these, preventing wasted GPU cluster cycles and cloud carbon emissions.")
pdf.speaker_notes("Slide 4 addresses sustainability. By running local deterministic evaluation, AgentShield incurs zero API fees. Crucially, we prevent hallucination loops, saving massive amounts of compute power and enterprise cost.")

pdf.add_page()
pdf.slide_title("SLIDE 5 OF 5: Progress Achieved Till Mid-Sem & Remaining Roadmap")
pdf.slide_section("Progress Accomplished Till Mid-Semester Review")
pdf.bullet_point("Core Security Gateway & Routing Engine fully operational.")
pdf.bullet_point("3-Tier Risk Engine & Heuristics implemented (DAN prompts, SQLi, wildcards).")
pdf.bullet_point("Real-time Human-in-the-Loop (HITL) approval manager built.")
pdf.bullet_point("Interactive Custom Terminal Dashboard: A live web portal allowing evaluators to test custom attacks in real-time.")
pdf.bullet_point("Rigorous Verification: 57 automated PyTest integration tests passing across 15 enterprise schemas.")
pdf.slide_section("Remaining Roadmap for End-Semester Review")
pdf.bullet_point("1. Production Containerization: Packaging the gateway into Docker Compose for one-click deployment.")
pdf.bullet_point("2. Multi-Agent Orchestration Support: Expanding proxy to handle simultaneous Swarm agent routing.")
pdf.bullet_point("3. Enterprise RBAC & OAuth2: Associating agent capabilities with organizational user roles.")
pdf.speaker_notes("Slide 5 covers our progress. The core proxy, risk engine, HITL approval, custom terminal, and 57 tests are complete! For the end-sem, we will focus on Docker deployment, multi-agent orchestration, and enterprise RBAC.")

pdf.output("AgentShield_Presentation_Deck.pdf")
print("PDF Generated successfully.")
